########################################################
# This script is associated with NNScore2.01.01_csv.py #
# It fetches all the csv file (generated by nnscore for#
#  each of the pdb ids) inside the 'output' directory  #
#  and merges to a single csv file.                    #
# 																		 #
# Written by Mahmudulla Hassan								 #
# Last modified: 02/07/2018									 #
########################################################

import glob
import csv

path = r'output' # use your path
allFiles = glob.glob(path + "/*.csv")

fout=open("all_predicted_values.csv", "a")

for file in allFiles:
    f = open(file)
    for line in f:
        fout.write(line)
    f.close()
fout.close()
